substitutions:
  name: esphome
  friendly_name: ESPHome
  device_name: "powmr-inverter"
  node_name: "PowMr Inverter"
  node_id: powmr_inverter
  inverter_tx_pin: GPIO16
  inverter_rx_pin: GPIO17
  inverter_voltage_offset: "0"
  pzem_tx_pin: GPIO1
  pzem_rx_pin: GPIO3
  pzem_voltage_offset: "1"
  pzem_current_offset: "0.04"
  update_interval: 10s # Minimum 10s recommended to avoid duplicate command errors
  select_skip_updates: "2"
  pzem_update_interval: 2s # Needs to be 1/5 of update interval because of smoothing filter on pzem readings


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "Monitor and control a PowMr inverter"
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3


esp32:
  board: esp32dev
  framework:
    type: esp-idf
  
    
packages:
  main: !include powmr-inverter/main.yaml
  
  
dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true  


logger:
  level: WARN
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"


time:
  - platform: homeassistant
    id: hass_time
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${node_name} Fallback"
    password: !secret ap_password


ota:
  platform: esphome
  id: "${node_id}_ota"
  password: !secret ota_password


api:
  reboot_timeout: 10min
  encryption:
    key: !secret api_encryption_key


captive_portal:


sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: "diagnostic"
    device_class: duration
    update_interval: 60s
  - platform: wifi_signal
    name: "RSSI"
    id: wifi_rssi
    entity_category: "diagnostic"
    update_interval: 60s
