esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control a PowMr inverter"
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3

packages:
  inverter: !include {
    file: modules/inverter.yaml
  }
  pzem: !include {
    file: modules/pzem.yaml
  }
  voltage-registers: !include {
    file: modules/voltage-registers.yaml
  }
#  voltage config write registers, 24V battery
#  voltage-registers: !include modules/voltage-registers.yaml
# 48V battery, uncomment this lines:

  debug: !include modules/debug.yaml

number:
  - id: !extend back_to_utility_source_voltage
    min_value: 45
    max_value: 51
    step: 1
  - id: !extend back_to_battery_source_voltage
    min_value: 48
    max_value: 58
    step: 1
  - id: !extend bulk_charging_voltage
    min_value: 48
    max_value: 61
  - id: !extend floating_charging_voltage
    min_value: 48
    max_value: 61

logger:
  baud_rate: 0

sensor:
  - platform: internal_temperature
    name: "Controller Temperature"
    update_interval: 10s
    state_class: measurement
    device_class: temperature
